# Generated by Django 2.0.3 on 2018-04-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporter', '0002_auto_20180409_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
