# Generated by Django 2.0.3 on 2018-04-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporter', '0003_auto_20180418_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=10)),
                ('date_added', models.DateTimeField()),
                ('user', models.CharField(max_length=150)),
            ],
        ),
    ]
